# Generated by Django 5.2.18 on 2026-10-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_id', models.CharField(max_length=50, unique=True)),
                ('donor_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('hub', models.CharField(max_length=50)),
                ('date', models.CharField(blank=True, max_length=50)),
                ('purpose', models.CharField(max_length=200)),
                ('status', models.CharField(default='pledged', max_length=50)),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('recurring', models.BooleanField(default=False)),
                ('items_count', models.IntegerField(blank=True, default=0, null=True)),
                ('item_category', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('theme_color', models.CharField(max_length=20)),
                ('image_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ImpactMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_beneficiaries', models.IntegerField(default=0)),
                ('total_volunteers', models.IntegerField(default=0)),
                ('active_centers', models.IntegerField(default=0)),
                ('funds_raised', models.IntegerField(default=0)),
                ('trees_planted', models.IntegerField(default=0)),
                ('meals_served', models.IntegerField(default=0)),
                ('monthly_growth_rate', models.FloatField(default=0)),
                ('donor_retention_rate', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('grade', models.CharField(max_length=20)),
                ('center', models.CharField(max_length=100)),
                ('subjects', models.JSONField(default=list)),
                ('enrollment_date', models.CharField(blank=True, max_length=50)),
                ('attendance_rate', models.IntegerField(default=0)),
                ('performance', models.CharField(default='new', max_length=50)),
                ('mentor_id', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('hub', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('skills', models.JSONField(default=list)),
                ('hours_contributed', models.IntegerField(default=0)),
                ('join_date', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='active', max_length=20)),
                ('avatar_color', models.CharField(default='#6366F1', max_length=20)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
